---
title: "Create database from data frame `mtcars`"
author: "Alex"
date: "`r format(Sys.time(), '%d %B %Y, %H:%M:%S')`"
output: 
  html_document:
    df_print: paged
    toc: true
    number_sections: false
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(RSQLite)
```

```{r}
head(mtcars)
```

```{r}
#' Add an ID Column to a Data Frame
#' 
#' Adds an `id` column to a data frame, populated with IDs as character 
#' strings ranging from 1 to the number of rows.
#' 
add_id_col <- function(x) {
  x$id = as.character(seq_len(nrow(x)))
  return(x)
}
```

```{r}
#' Convert a Vector to Integer Character Label
#'
#' Converts a vector into a factor, and then into a vector of labels ranging 
#' from 1 to the number of factor levels.
#'
as.cif <- function(x) {
  as.character(as.integer(as.factor(x)))
}
```

```{r}
# Using dplyr:
# z <- mtcars %>%
#   mutate(make = rownames(mtcars),
#          id = as.character(row_number()), # as.character(1:nrow(mtcars))
#          cyl_id = as.cif(cyl),
#          vs_id = as.cif(vs),
#          am_id = as.cif(am),
#          gear_id = as.cif(gear),
#          carb_id = as.cif(carb))
# rownames(z) <- 1:nrow(mtcars)
```

Using base R:

```{r}
# z <- mtcars
# z$make <- rownames(mtcars)
# z <- add_id_col(z)
# z <- within(z, {
#   make = rownames(mtcars)
#   cyl_id = as.cif(cyl)
#   vs_id = as.cif(vs)
#   am_id = as.cif(am)
#   gear_id = as.cif(gear)
#   carb_id = as.cif(carb)
# })
# rownames(z) <- 1:nrow(z)

z <- mtcars |>
  transform(
    make = rownames(mtcars),
    cyl_id = as.cif(cyl),
    vs_id = as.cif(vs),
    am_id = as.cif(am),
    gear_id = as.cif(gear),
    carb_id = as.cif(carb)
  ) |>
  add_id_col() |>
  {\(data) { rownames(data) <- 1:nrow(data); data }}()
```

Create table of cars specifications

```{r}

```

```{r}
# Using dplyr
# specs_table <- z %>%
#   dplyr::select(id, mpg, disp:qsec)
# head(specs_table)

# Using base R
specs_table <- z[, c("id", "mpg", "disp", "hp", "drat", "wt", "qsec")]
head(specs_table)
```

Table of cyl

```{r}
# Using dplyr
# cyl_table <- z %>%
#   select(cyl, cyl_id) %>%
#   distinct() %>%
#   arrange(cyl) %>%
#   mutate(cyl = as.character(cyl))
# cyl_table

# Using base R and |> pipe
cyl_table <- z[, c("cyl", "cyl_id")] |>
  unique() |>
  (\(df) df[order(df$cyl_id), ])() |>
  (\(df) { df$cyl <- as.character(df$cyl); df })() |>
  (\(df) { rownames(df) <- NULL; df })()
cyl_table
```

Table of vs

```{r}
# Using dplyr
# vs_table <- z %>%
#   select(vs, vs_id) %>%
#   distinct() %>%
#   arrange(vs) %>%
#   mutate(vs = as.character(vs))
# vs_table

# Using base R and |> pipe
vs_table <- z[, c("vs", "vs_id")] |>
  unique() |>
  (\(df) df[order(df$vs_id), ])() |>
  (\(df) { df$vs <- as.character(df$vs); df })() |>
  (\(df) { rownames(df) <- NULL; df })()
vs_table
```

Table of am

```{r}
# Using dplyr
# am_table <- z %>%
#   select(am, am_id) %>%
#   distinct() %>%
#   arrange(am) %>%
#   mutate(am = as.character(am))
# am_table

# Using base R and |> pipe
am_table <- z[, c("am", "am_id")] |>
  unique() |>
  (\(df) df[order(df$am_id), ])() |>
  (\(df) { df$am <- as.character(df$am); df })() |>
  (\(df) { rownames(df) <- NULL; df })()
am_table
```

Table of gear

```{r}
# Using dplyr
# gear_table <- z %>%
#   select(gear, gear_id) %>%
#   distinct() %>%
#   arrange(gear) %>%
#   mutate(gear = as.character(gear))
# gear_table

# Using base R and |> pipe
gear_table <- z[, c("gear", "gear_id")] |>
  unique() |>
  (\(df) df[order(df$gear_id), ])() |>
  (\(df) { df$gear <- as.character(df$gear); df })() |>
  (\(df) { rownames(df) <- NULL; df })()
gear_table
```

Table of carb

```{r}
# Using dplyr
# carb_table <- z %>%
#   select(carb, carb_id) %>%
#   distinct() %>%
#   arrange(carb) %>%
#   mutate(carb = as.character(carb))
# carb_table

# Using base R and |> pipe
carb_table <- z[, c("carb", "carb_id")] |>
  unique() |>
  (\(df) df[order(df$carb_id), ])() |>
  (\(df) { df$carb <- as.character(df$carb); df })() |>
  (\(df) { rownames(df) <- NULL; df })()
carb_table
```

Table of cars

```{r}
cars_table <- z %>%
  select(id, make, cyl_id, vs_id, am_id, gear_id, carb_id) %>%
  mutate(id = as.numeric(id)) %>%
  distinct() %>%
  arrange(id) %>%
  mutate(id = as.character(id))
head(cars_table)
```

```{r}
cars_table <- y[, c("id", "make", "cyl_id", "vs_id", "am_id", "gear_id", "carb_id")] |>
  unique() |>
  (\(df) df[order(df$id), ])() |>
  (\(df) { df$id <- as.character(df$id); df })() |>
  (\(df) { rownames(df) <- NULL; df })()
cars_table
```

Rejoin

```{r}
df <- cars_table %>% 
  right_join(., cyl_table, by = "cyl_id") %>% 
  right_join(., vs_table, by = "vs_id") %>% 
  right_join(., am_table, by = "am_id") %>%
  right_join(., gear_table, by = "gear_id") %>% 
  right_join(., carb_table, by = "carb_id") %>% 
  select(c(id, make, cyl, vs, am, gear, carb)) %>% 
  right_join(., specs_table, by = "id") %>%
  as_tibble()
head(df)
```

Reorder columns and fix data types

```{r}
df <- as.data.frame(df)
rownames(df) <- df$make
df <- df %>%
  select(mpg, cyl, disp:qsec, vs:carb) %>%
  mutate(across(.cols = c(cyl, vs, am, gear, carb), .fns = ~ as.numeric(.x)))
head(df)
```

The constructed data frame is identical to the original

```{r}
identical(mtcars, df)
```

A more relaxed equivalence test, ignoring the row order:

```{r}
nrow(setdiff(mtcars, df)) == 0
```

Create database

```{r}
con <- dbConnect(RSQLite::SQLite(), "mtcars.sqlite")
```

```{r}
dbWriteTable(conn = con, name = "caritems", value = cars_table)
dbWriteTable(con, "cyl", cyl_table)
dbWriteTable(con, "vs", vs_table)
dbWriteTable(con, "am", am_table)
dbWriteTable(con, "gear", gear_table)
dbWriteTable(con, "carb", carb_table)
dbWriteTable(con, "techprop", specs_table)
```

```{r}
dbListTables(con)
```

Close the database connection

```{r}
dbDisconnect(con)
```

Cleanup

```{r}
file.remove("mtcars.sqlite")
```
